# Generated by Django 3.2.5 on 2021-07-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField()),
                ('email', models.EmailField(default=True, max_length=100)),
                ('Address', models.TextField(default=True, max_length=100)),
                ('gender', models.CharField(default=True, max_length=10)),
                ('country', models.CharField(default=True, max_length=10)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.group')),
            ],
        ),
    ]
